namespace Warcraft.NET.Docs
{
    internal static class ChunkAvailability
    {
        internal static Dictionary<string, Dictionary<string, List<string>>> Chunks = new()
        {
            {
                "adt", new ()
                {
                    {
                        "ADT", new()
                        {
                            "MVER",
                            "MHDR",
                            "MCIN",
                            "MTEX",
                            "MMDX",
                            "MMID",
                            "MWMO",
                            "MWID",
                            "MDDF",
                            "MODF",
                            "MH2O",
                            "MCNK",
                            "MCCV",
                            "MCLV",
                            "MCNR",
                            "MCSE",
                            "MCVT",
                            "MFBO",
                            "MTXF",
                        }
                    },
                    {
                        "_tex0 ADT", new()
                        {
                            "MVER",
                            "MTEX",
                            "MDID",
                            "MHID",
                            "MCNK",
                            "MCSH",
                            "MCAL",
                            "MCLY",
                            "MCMT",
                            "MAMP",
                            "MTXP",
                            "MTXF",
                            "MTCG",
                        }
                    },
                    {
                        "_obj0 ADT", new()
                        {
                            "MVER",
                            "MCNK",
                            "MCRD",
                            "MCRW",
                            "MMDX",
                            "MMID",
                            "MWMO",
                            "MWID",
                            "MDDF",
                            "MODF",
                            "MWDR",
                            "MWDS",
                            "MLMB",
                        }
                    },
                    {
                        "_obj1 ADT", new()
                        {
                            "MVER",
                            "MLDL",
                            "MLFD",
                            "MLDD",
                            "MLDX",
                            "MLMD",
                            "MLMX",
                            "MLDB",
                            "MLMB",
                        }
                    },
                    {
                        "_lod ADT", new()
                        {
                            "MVER",
                            "MLHD",
                            "MLVH",
                            "MLLL",
                            "MLND",
                            "MLVI",
                            "MLSI",
                            "MLLD",
                            "MLLN",
                            "MLLI",
                            "MLLV",
                            "MLMB",
                        }
                    },
                }
            },
            {
                "m2", new ()
                {
                    {
                        "M2", new()
                        {
                            "MD21",
                            "PFID",
                            "SFID",
                            "AFID",
                            "BFID",
                            "TXAC",
                            "EXPT",
                            "EXP2",
                            "PABC",
                            "PADC",
                            "PSBC",
                            "PEDC",
                            "SKID",
                            "TXID",
                            "LDV1",
                            "RPID",
                            "GPID",
                            "WFV1",
                            "WFV2",
                            "PGD1",
                            "WFV3",
                            "PFDC",
                            "EDGF",
                            "NERF",
                            "DETL",
                            "DBOC",
                            "AFRA",
                        }
                    },
                }
            },
            {
                "tex", new ()
                {
                    {
                        "TEX", new()
                        {
                            "TXVR",
                            "TXBT",
                            "TXFN",
                            "TXMD"
                        }
                    },
                }
            },
            {
                "wdl", new ()
                {
                    {
                        "WDL", new()
                        {
                            "MVER",
                            "MAOF",
                            "MARE",
                            "MAHO",
                            "MWMO",
                            "MWID",
                            "MODF",
                            "MLDD",
                            "MLDX",
                            "MLMD",
                            "MLMX",
                            "MAOC",
                            "MAOE",
                            "MSSN",
                            "MSSC",
                            "MSSO",
                        }
                    },
                }
            },
            {
                "wdt", new ()
                {
                    {
                        "Root WDT", new()
                        {
                            "MVER",
                            "MPHD",
                            "MAIN",
                            "MAID",
                            "MWMO",
                            "MODF",
                            "MANM",
                        }
                    },
                    {
                        "_occ WDT", new()
                        {
                            "MVER",
                            "MPHD",
                            "MAIN",
                            "MAID",
                            "MWMO",
                            "MODF",
                            "MANM",
                        }
                    },
                    {
                        "_lgt WDT", new()
                        {
                            "MVER",
                            "MPLT",
                            "MPL2",
                            "MPL3",
                            "MSLT",
                            "MTEX",
                            "MLTA",
                        }
                    },
                    {
                        "_fogs WDT", new()
                        {
                            "MVER",
                            "VFOG",
                            "VFEX",
                        }
                    },
                    {
                        "_mpv WDT", new()
                        {
                            "MVER",
                            "PVPD",
                            "PVMI",
                            "PVBD",
                        }
                    },
                }
            },
            {
                "wmo", new ()
                {
                    {
                        "Root WMO", new()
                        {
                            "MVER",
                            "MOHD",
                            "MOTX",
                            "MOMT",
                            "MOM3",
                            "MOUV",
                            "MOGN",
                            "MOGI",
                            "MOSB",
                            "MOSI",
                            "MOPV",
                            "MOPT",
                            "MOPR",
                            "MOVV",
                            "MOVB",
                            "MOLT",
                            "MOLV",
                            "MODS",
                            "MODN",
                            "MODI",
                            "MODD",
                            "MFOG",
                            "MCVP",
                            "GFID",
                            "MDDI",
                            "MPVD",
                            "MAVG",
                            "MAVD",
                            "MBVD",
                            "MFED",
                            "MGI2",
                            "MNLD",
                            "MDDL",
                        }
                    },
                    {
                        "Group WMO", new()
                        {
                            "MVER",
                            "MOGP",
                            "MOGX",
                            "MOPY",
                            "MPY2",
                            "MOVI",
                            "MOVT",
                            "MONR",
                            "MOTV",
                            "MOLV",
                            "MOBA",
                            "MOQG",
                            "MOLR",
                            "MODR",
                            "MOBN",
                            "MOBR",
                            "MOCV",
                            "MOC2",
                            "MLIQ",
                            "MORI",
                            "MOTA",
                            "MOBS",
                            "MDAL",
                            "MOPL",
                            "MOPB",
                            "MOLS",
                            "MOLP",
                            "MLSS",
                            "MLSP",
                            "MLSO",
                            "MLSK",
                            "MOS2",
                            "MOP2",
                            "MPVR",
                            "MAVR",
                            "MBVR",
                            "MFVR",
                            "MNLR",
                        }
                    },
                }
            },
        };
    }
}
